config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'comics#index'
  resources :comics, only: [:index, :new, :create, :show] do
     resources :comments, only: [:index, :new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image


with_options presence: true do
  validates :title
  validates :summary
  validates :user
  validates :image
  validates :link
end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :comic

  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comics
  has_many :rooms, through: :comics
  # has_many :comic_rooms
  has_many :messages 
  with_options presence: true do
    validates :email
    validates :nickname
  end
  VALID_PASSWORD_REGIX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,}+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGIX, message: 'Include both letters and numbers' }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_parmitted_parameters, if: :devise_controller?
  protected



  def configure_parmitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end


end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
before_action :basic_auth, only: [:new]




  def index 
    @comics = Comic.includes(:user).all
  end

  def new
    @comic = Comic.new
  end

  def create
    @comic = Comic.new(comic_params)
    if @comic.save
      redirect_to root_path
    else 
      render :new
    end
    
  end

def show
  @comic = Comic.find(params[:id])
  # @comments = Comment.where(comic_id: @comic.id)
  @comments = @comic.comments.includes(:comic)
end




private
def comic_params
  params.require(:comic).permit(:image, :title, :summary, :link).merge(user_id: current_user.id)
end
  

def comment_params
  params.require(:comment).permit(:name).merge(user_id: current_user.id, comic_id: params[:comic_id])
end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
  end


  def new
    @comment = Comment.new
  end


  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to root_path
    else 
        render :new
    end
  end


  def show
  end


  private
 
  def comment_params
    params.require(:comment).permit(:name, :text).merge(comic_id: params[:comic_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/comics/_comic.html.erb
<li class='list'>
<%= link_to comic_path(comic.id) do %>
<%= image_tag comic.image, class: "comic-img" %>
<h3 class='comic-title'>
  <%= comic.title %>
 </h3>
<% end %>

</li>

app/views/comics/_comment.html.erb
<li>
 <div class='comment'>
 <% if comment.name.present? %>
  <h3 class='comment-name'>
    <%= comment.name %>
  </h3>
<% else %>
  <h3 class='comment-name'>
    名無しです
  </h3>
<% end %>  
  <h3 class='comment-text'> 
    <%= comment.text %>
  </h3>
 </div>
  <h3 class='comment-time'>
    <%= comment.created_at.to_s(:datetime) %>
  </h3>
</li>

app/views/comics/index.html.erb
<%# CSS・・・assets/stylesheets/comics/index.css %>
<%= render "shared/header" %>
 <div class = "main">

   <div class="introduction">
   <div class='introduction-text'>
      <p>皆様こんにちは、当サイトはみんなが好きな漫画について熱く語っちゃう掲示板です</p>
      <p>暴言等はお控え下さい、マナーを守って楽しく語りましょう</p>
      <p>満足するまでゆっくりしていってね</p>
   </div>
  </div>


   <div class = comics_container>
      <%= render partial: "comic", collection: @comics %> 
   </div>









 </div>

app/views/comics/new.html.erb
<%= render "shared/header" %>
   <%= form_with(model: @comic, local: true) do |f| %>


    <%= render 'shared/error_messages', model: f.object %>
    
    <div class="img-upload">
      <div class="weight-bold-text">
        <p>漫画画像</p>
      </div>
      <div class="click-upload">
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

        <div class="new-items">
      <div class="weight-bold-text">
        漫画名
      </div>
      <%= f.text_field :title, class:"comics-text", id:"comic-name", placeholder:"漫画名", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          <p>あらすじ</p>
        </div>
        <%= f.text_area :summary, class:"comix-text", id:"comic-info", placeholder:"あらすじ" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <div class="link">
    リンク
    </div>
    <%= f.text_field :link, class:"link-name", id:"link-name", placeholder:"link" %>

    

        <div class="toukou-btn-contents">
      <%= f.submit "投稿する" ,class:"toukou-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/comics/show.html.erb
<%= render "shared/header" %>

<div class="comic-show">
  <div class="item-box">
    <div class='item-img-content'>
      <%= image_tag @comic.image ,class:"comic-box-img" %>
    </div>
    <h2 class="comic-name">
      <%= @comic.title %>
    </h2>
  </div>
  <div class="summary-link">
    <div class="comic-summary">
        <%= @comic.summary %>
    </div>
    <div class="comic-link">
      <%= raw Rinku.auto_link(h(@comic.link)) %>
    </div>
    </div>
</div>

<div class="comment-container">

<div class='new_comments'>
<%= link_to '新規投稿する', new_comic_comment_path(@comic) %>
</div>



 <div class="page-container">
 <%if @comments.any? %>
  <ul class='content-list'>
    <%= render partial: "comment", collection: @comments %>
  </li>
 <% else %>
<li class ='content'>
  <p>ここはあなたが好きなように語っていい場所です</p>
  <p>好きなお題を提供して下さい</p>
</li>
<% end %>

</div>

</div>

app/views/comments/new.html.erb
<%= render "shared/header" %>
   <%= form_for @comment,:url => {:action => :create} do |f| %>
   <%= render 'shared/error_messages', model: f.object %>
   <%= f.text_field :name, class:"name", id:"name", placeholder:"名前", maxlength:"40" %>
   <%= f.text_field :text, class:"text", id:"text", placeholder:"投稿文", maxlength:"1000" %>
        <div class="toukou-btn-contents">
      <%= f.submit "投稿する" ,class:"toukou-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MangaKeijiban</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/new.html.erb
<%= render "shared/header" %>
   <%= form_for @room,:url => {:action => :create} do |f| %>
   <%= render 'shared/error_messages', model: f.object %>
   <%= f.text_field :name, class:"name", id:"name", placeholder:"スレッド名", maxlength:"40" %>
   <%= f.text_field :text, class:"text", id:"text", placeholder:"投稿文", maxlength:"1000" %>
        <div class="toukou-btn-contents">
      <%= f.submit "投稿する" ,class:"toukou-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class= 'header_a'>
<div class = "container">
 <div class = "area_logo_header">
  <div class="ham-whole">
    <input type="checkbox" id="ham-check">
    <label for="ham-check" class="ham-open">
        <span></span>
    </label>
    <nav>
        <ul>
          <%= render partial: "comics/comic", collection: @comics %> 
        </ul>
    </nav>
 </div>
  <%= link_to image_tag("logo.png" ,class:"logo"), root_path %>
  </div> 


<div id="menu-background"></div>

  <%# ログイン等のページ遷移 %>
  <nav class = "area_nav_header">
    <ul class ="list_nav_header">
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_session_path, class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
        <%= link_to(new_comic_path, class: 'purchase-btn') do %>
        <%= image_tag 'kamisama.png' , size: '20x20' ,class: "purchase-btn-icon" %>
         <% end %>
       <% else %>
         <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
         <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
  </nav>
 </div>
</header>